### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jonatrey** [ajph/bitstamp-go#11]
I would like to contribue, could you add a standard license ? I suggest MIT, the standard template can be found on Wikipedia. Could be LGPL, GPL, Apache 2...

**Comment by ajph** [comment]
Yes absolutely, great idea. MIT is fine. I'll add it when I get a chance - feel free to submit a PR if you get to it before I do

**Comment by jonatrey** [comment]
MIT license requires your full name or company you are working for. See https://help.github.com/articles/adding-a-license-to-a-repository/ - pretty straightforward.

**Comment by ajph** [comment]
This is addressed in 2418260ca7960de4db07fb0b4a1036f769050f6d
